spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행하는 SQL을 콘솔에 출력
        format_sql: true # 실행되는 SQL의 들여쓰기 및 줄 개행
        use_sql_comments: true
    hibernate:
      ddlAuto: create


# 로거 설정
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.bind: trace